### ISSUE TITLE
API sytle in gForceSDKArduino

### ISSUE THREAD

**Issue by zhoukaidev** [oymotion/gForceSDKArduino#3]
## brief
The most important users of Arduino are beginners and people who don't care about code ,so the api style is the point we should focus on. It is obviously that the api style in gForceSDKArduino is unfriendly,especially the pointer , scope operator etc.

There are [API style guide](https://www.arduino.cc/en/Reference/APIStyleGuide) and [Arduino style guide](https://www.arduino.cc/en/Reference/StyleGuide) provided by Arduino

**Comment by zhoukaidev** [comment]
###  Reference guide 
[Arduino library specifications](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) is a good resource

**Comment by joeyu** [comment]
@saber-hyw Please take a look at it to see if any changes or improvements are needed. Thanks!

**Comment by LdFelix** [comment]
我使用Arduino UNO运行了Arduino的示例程序，有下面的错误，请问如何解决
![image](https://user-images.githubusercontent.com/34497803/61038409-95fec300-a3ff-11e9-8c0a-c0af74299e41.png)
