### ISSUE TITLE
使用mega2560编译示例程序，提示编译错误

### ISSUE THREAD

**Issue by XavierCao** [oymotion/gForceSDKArduino#5]
如图，使用mega2560上传示例程序，报错
![image](https://user-images.githubusercontent.com/34497803/61058244-6d8bbe80-a429-11e9-9715-db197fbe8238.png)

**Comment by RafaelSilvaUW** [comment]
I'm having the exact same issue... Do we have a fix for this?

Any help is VERY welcome! Thanks.

**Comment by LdFelix** [comment]
I have more important things to do, so I can't continue to explore this issue, sorry......

**Comment by XavierCao** [comment]
> I'm having the exact same issue... Do we have a fix for this?
> 
> Any help is VERY welcome! Thanks.

I have more important things to do, so I can't continue to explore this issue, sorry......

**Comment by RafaelSilvaUW** [comment]
That's ok. I was able to run the code from one commit before this one... this workaround can help other people facing the same issue.

**Comment by BigBro2014** [comment]
It's caused by wrong function name of delay and get tick. Now it's fixed.
