### ISSUE TITLE
Why is there 16 values for raw EMG?

### ISSUE THREAD

**Issue by eunaoquero** [oymotion/gForceSDKArduino#7]
Hello,

Why in the gForceDataTypes.h, the data structure for raw EMG has 16 values?

struct GF_Emgraw
{
  unsigned char raw[16];
};

I'm able to play around with these values, but I'm not quite sure what data I'm working with. Can you, please, provide some clarification why is there 16 data streams for raw EMG? Is the information from each 8 sensors broken down in 2 slots of that data structure? 

Thank you very much in advance for your advice.

**Comment by BigBro2014** [comment]
Well, the EMG data is used for our special device. It's not intented for gForcePro armband.
